name: Test

on: [push, pull_request]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test-php:
        name: Test PHP ${{ matrix.php }} ${{ matrix.wp != '' && format( ' (WP {0}) ', matrix.wp ) || '' }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                  - '8.3'
                  - '8.2'
                  - '8.1'
                  - '8.0'
                  - '7.4'
                  - '7.3'
                  - '7.2'
                wp:
                  - latest
                  - trunk
                  - '6.3'
        env:
            WP_ENV_PHP_VERSION: ${{ matrix.php }}
            WP_ENV_CORE: ${{ matrix.wp == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wp ) }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                cache: 'npm'
                node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm install

            - name: Start the Docker testing environment
              uses: nick-fields/retry@v3
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: npx wp-env start

            - name: Install Composer dependencies
              run: |
                rm composer.lock || true # We want to do this fresh.
                npm run composer install

            - name: Versions
              run: |
                npx wp-env run cli php -- -v
                npx wp-env run cli wp core version
                npx wp-env run cli wp eval 'echo "PHP: " . phpversion() . "; WP: " . $GLOBALS["wp_version"];'
                npx wp-env run tests-cli phpunit -- --version
                npm run phpunit -- --version
                npm run composer -- --version
                npm run composer test -- --version

            - name: Run the Tests
              run: npm run phpunit

